# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  # push:
  #   branches: [master]
  pull_request:
    branches: [master, develop]

jobs:
  PR_lint:
    name: Pull Request style check
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Pull Request Style Check
        # You may pin to the exact commit or the version.
        # uses: maximbircu/pull-request-checkstyle@c28d5560bc74eb67e7a6fd431c3169f5908b8682
        uses: maximbircu/pull-request-checkstyle@v1.0.0
        with:
          # Regex to validate the commit message title (Validates just the first line of the commit message)
          commit-message-title-regex: ".*" # optional, default is .*
          # Min commit message title length (Validates just the first line of the commit message)
          commit-message-title-min-length: 10 # optional, default is 10
          # Max commit message title length (Validates just the first line of the commit message)
          commit-message-title-max-length: 180 # optional, default is 72
          # Regex to validate the branch name
          branch-name-regex: '[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+' # optional, default is .*
          # Min branch name length
          branch-name-min-length: 10 # optional, default is 10
          # Max branch name length
          branch-name-max-length: 72 # optional, default is 72

  code_lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3.15.5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_JAVASCRIPT_STANDARD: false
          # VALIDATE_PYTHON_BLACK: true
          # VALIDATE_PYTHON_FLAKE8: false
          # VALIDATE_PYTHON_ISORT: false
          # VALIDATE_PYTHON_MYPY: false
          # VALIDATE_PYTHON_PYLINT: false
          # Flag to have the linter complete with exit code 0 even if errors were detected.
          # DISABLE_ERRORS: true

  build:
    name: Builds and test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # - name: Test
      #   run: npm run test --if-present

#   deploy:
#     name: Deploy to heroku
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#     - name: Deploy to Heroku
#       uses: AkhileshNS/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
#           heroku_email: "YOUR EMAIL"
